services:
  api:
    build: .
    env_file:
      - .env.test
    depends_on:
      mongo-test:
        condition: service_healthy

  mongo-test:
    image: mongo:5
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping') || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12