services:
  mongo-test:
    image: mongo:latest
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval 'db.adminCommand(\"ping\")' || exit 1"]      
      interval: 2s
      timeout: 2s
      retries: 10

  api:
    build: .
    env_file:
      - .env.test
    depends_on:
      mongo-test:
        condition: service_healthy