GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6990a488d3b1a5ece3056bea

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Speedylo",
    "subscribedToChannel": "Siphano" 
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Wassimosio",
    "subscribedToChannel": "Frigiel" 
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Wassimosio",
    "subscribedToChannel": "LaSalle" 
}

###

DELETE http://localhost:3000/subscribers/699216bc3932abfb6c0dc6eb

### 

PATCH http://localhost:3000/subscribers/64b8f9f9f9f9f9f9f9f9f9f9
Content-Type: application/json

{
    "name": "Random Name"
}

###

GET http://localhost:3000/health