GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/6990a488d3b1a5ece3056bea

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Speedylo",
    "subscribedToChannel": "Siphano" 
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Wassimosio",
    "subscribedToChannel": "Frigiel" 
}

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Wassimosio",
    "subscribedToChannel": "LaSalle" 
}

###

DELETE http://localhost:3000/subscribers/6990a5b047c74f5c4e60c9ed

### 

PATCH http://localhost:3000/subscribers/6990a5b047c74f5c4e60c9ed
Content-Type: application/json

{
    "name": "Random Name"
}

###

GET http://localhost:3000/health